### ISSUE TITLE
Polymorph overlaps with wireless terminal GUI

### ISSUE THREAD

**Issue by Mithi83** [62832/PolymorphicEnergistics#4]
Using a self-compiled version of the latest master branch, polymorph-neoforge-1.0.4+1.21 and ATM 10.0.14, I tried to replicate a bug I thought I had seen in some youtube video recently. In a wireless crafting terminal (or a ae2wtlib wireless universal terminal) the arrow to move the 3x3 input into the player inventory overlaps with the button for polymorph. Other GUIs, such as a crafting terminal or a pattern encoding terminal are fine.

I'm not sure in which way this should be fixed (AE2 or PolymorphicEnergistics), but since it only happens, when PolymorphicEnergistics is involved I will report it here first. Maybe a fix could be to move the down arrow to be x-aligned to the up arrow and moved to the bottom of the third input row in AE2, but since that involves GUI aesthetics it definitely not my call.

![wireless-crafting-polymorph](https://github.com/user-attachments/assets/47fc13d4-69d4-4ad7-b757-2a3babb0fa96)

**Comment by 62832** [comment]
For the time being, I've gone ahead and added some slight integration with AE2WTLib to move the widget down below the slot rather than above if the menu happens to be a wireless crafting terminal specifically from the add-on.

**Comment by Mithi83** [comment]
I just confirmed the fix. I was a bit surprised to learn that ae2wtlib changed the look of the wireless crafting terminal from AE2 if it is installed.

Thanks for the quick update!
